notifications:
  email: false

sudo: required

services:
  - docker

git:
  depth: false

script:
  - docker build . -t renku/renku-demo

deploy:
  - &script
    provider: script
    skip_cleanup: true
    script: bash travis-deploy.sh
    on: &script_on
      branch: master
      repo: SwissDataScienceCenter/renku-demo
  - <<: *script
    on:
      <<: *script_on
      tags: true
